#pragma config(Motor,  port1,           FR,            tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port2,           BR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          FL,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Stores the state of the program
bool running = true;

task main()
{
    //Loops until the program is not running any more
    while (running)
    {
        //Updates the front motors using the left joystick
        motor[FL] = vexRT(Ch3);
        motor[FR] = vexRT(Ch4);

        //Updates the back motors using the right joystick
        motor[BL] = vexRT(Ch2);
        motor[BR] = vexRT(Ch1);

        //Exits the program if both of the U sholder buttons are pressed
        if (vexRT(Btn5U) == true && vexRT(Btn6U) == true)
        {
            running = false;
        }
    }
}