#pragma config(Sensor, dgtl2,  Relay,          sensorDigitalOut)
#pragma config(Motor,  port1,           FR,            tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port2,           BR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          FL,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Stores the state of the program
bool running = true;

bool isRelayOn = false;

//Stores the movement value for the left and right motors
short dirx = 0;
short diry = 0;
short Ls = 0;
short Rs = 0;

task main()
{
    //Loops until the program is not running any more
    while (running)
    {

    dirx = vexRT(Ch4);
    diry = vexRT(Ch3);

    //Q1
    if (diry > 0 && dirx > 0){
    if(diry >= dirx)
    {
    Ls = abs(diry/dirx *10);
    Rs = abs(dirx/diry *10);
    }
    else
    {
    Ls = abs(diry/dirx *10);
    Rs = -abs(dirx/diry *10);
    }
    }
    //Q2
    if (diry > 0 && dirx < 0){

    if(diry >= dirx)
    {
    Ls = abs(dirx/diry *10);
    Rs = abs(diry/dirx *10);
    }
    else
    {
    Ls = -abs(diry/dirx *10);
    Rs = abs(dirx/diry *10);
    }
    }
    //Q4
    if (diry < 0 && dirx > 0){

    if(abs(diry) >= dirx)
    {
    Ls = -abs(dirx/diry*10);
    Rs = -abs(diry/dirx*10);
    }
    else
    {
    Ls = abs(dirx/diry*10);
    Rs = -abs(diry/dirx*10);
    }
    }
    //Q3
    if (diry < 0 && dirx < 0){

    if(abs(diry) >= dirx)
    {
    Ls = -abs(diry/dirx*10);
    Rs = -abs(dirx/diry*10);
    }
    else
    {
    Ls = abs(diry/dirx*10);
    Rs = -abs(dirx/diry*10);
    }
    }
    //y = 0
    if (diry == 0)
    {
    Rs = dirx;
    Ls = -Rs;
    }
    //x = 0
    if (dirx == 0)
    {
    Rs = diry;
    Ls = Rs;
    }

    motor[FL] = Ls;
    motor[BL] = Ls;
    motor[FR] = Rs;
    motor[BR] = Rs;

    //////////////////////////////////

      if(SensorValue(Btn8R) == true)
      {
      isRelayOn = true;
      }
      else
      {
      isRelayOn = false;
      }

      SensorValue(Btn8R) = isRelayOn;


      //Exits the program if both of the U sholder buttons are pressed
      if (vexRT(Btn5U) == true && vexRT(Btn6U) == true)
      {
          running = false;
      }
    }
}
