#pragma config(Sensor, dgtl12, RelayN,         sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true == true)
	{
		// Turn on the relay
		SensorValue[RelayN] = 1;
		wait1Msec(500); // Wait for ha;f a second

		// Turn off the relay
		SensorValue[RelayN] = 0;
		wait1Msec(500);// Wait for ha;f a second
	}
}
