#pragma config(Motor,  port1,           FR,            tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           BR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          FL,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

  int num = 5;

  writeDebugStreamLine("Hello, World!");

  motor[FL] = 127; //Motor range between -127 <-> 127
  motor[FR] = 127; //Motor range between -127 <-> 127
  motor[BL] = 127; //Motor range between -127 <-> 127
  motor[BR] = 127; //Motor range between -127 <-> 127

  wait1Msec(1000);

  while(false)
  {

  	//motor[FL] = vexRT(Ch3);
  	//motor[FR] = vexRT(Ch3);
  }

}
