#pragma config(Sensor, dgtl2,  Relay,          sensorDigitalOut)
#pragma config(Motor,  port1,           FR,            tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port2,           BR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          FL,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define MIN(i, j) (((i) < (j)) ? (i) : (j))
#define MAX(i, j) (((i) > (j)) ? (i) : (j))


//Stores the state of the program
bool running = true;

bool isRelayOn = false;

//Stores the movement value for the left and right motors
short dirx = 0;
short diry = 0;
short Ls = 0;
short Rs = 0;

short maxDir = 127;
short minDir = -127;

short deadZn = 10;

task main()
{
    //Loops until the program is not running any more
    while (running)
    {

    	//leftDiry = vexRT(Ch3);
    	//rightDiry = vexRT(Ch3);
    //	leftDirx = vexRT(Ch4);
  //  	rightDirx = vexRT(Ch4);

    	dirx = vexRT(Ch4);
    	diry = vexRT(Ch3);




    	if(-deadZn <= dirx && dirx <= deadZn && -deadZn <= diry && diry <= deadZn)
    	{
    		Rs = 0;
    		Ls = 0;
    	}
    	if (dirx == 0 && diry == maxDir)
    	{
    		Rs = maxDir;
    		Ls = maxDir;
    	}
    	else if (dirx == minDir && diry == 0)
    	{
    		Rs = maxDir;
    		Ls = minDir;
    	}
    	else if (dirx == 0 && diry == minDir)
    	{
    		Rs = minDir;
    		Ls = minDir;
    	}
    	else if (dirx == maxDir && diry == 0)
    	{
    		Rs = minDir;
    		Ls = maxDir;
    	}
    	else
    	{
    		//Q1
	    	if (diry > 0 && dirx > 0){
	    		Ls = MAX(dirx, diry);
	    		Rs = diry - dirx;
	    	}
	    	//Q2
	    	if (diry > 0 && dirx < 0){
	    		Ls = diry + dirx;
	    		Rs = MAX(dirx, diry);
	    	}
	    	//Q3
	    	if (diry < 0 && dirx < 0){
	    		Ls = MIN(dirx, diry);
	    		Rs = diry - dirx;
	    	}
	    	//Q4
	    	if (diry < 0 && dirx > 0){
	    		//
	    		Rs = MIN(dirx, diry);
	    		Ls = dirx + diry;
	    	}
    	}

    	motor[FL] = Ls;
    	motor[BL] = Ls;
    	motor[FR] = Rs;
    	motor[BR] = Rs;
    	//motor[Fl] = (dirx + diry)/2




    //////////////////////////////////

      if(SensorValue(Btn8R) == true)
      {
      	isRelayOn = true;
      }
      else
      {
      	isRelayOn = false;
      }

      SensorValue(Btn8R) = isRelayOn;


      //Exits the program if both of the U sholder buttons are pressed
      if (vexRT(Btn5U) == true && vexRT(Btn6U) == true)
      {
          running = false;
      }
    }
}
